### ISSUE TITLE
Python Notice Send Custom Example Returns Attribute Error

### ISSUE THREAD

**Issue by cole-clark** [ColinKennedy/USD-Cookbook#1]
On Centos7, running this file returns the following error:

[notice_send_custom.py](https://github.com/ColinKennedy/USD-Cookbook/blob/master/concepts/notice_send/python/notice_send_custom.py)

```
Traceback (most recent call last):
  File "notice_send_custom.py", line 77, in <module>
    main()
  File "notice_send_custom.py", line 73, in main
    send_custom()
  File "notice_send_custom.py", line 62, in send_custom
    notice.Send(sender)
  File "notice_send_custom.py", line 40, in callback
    raise ValueError(notice.GetStage())
AttributeError: 'Notice' object has no attribute 'GetStage'
```

**Comment by ColinKennedy** [comment]
Ah, my bad. Looks like this example + notice_send_custom's C++ project were broken. They're both fixed now!
